# Generated by Django 4.0.3 on 2022-04-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDegrees', '0002_masterdegrees_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdegrees',
            name='image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
