# Generated by Django 4.0.3 on 2022-04-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDegrees', '0003_masterdegrees_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterdegrees',
            old_name='master_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='modules',
            old_name='module_code',
            new_name='code',
        ),
        migrations.AddField(
            model_name='modules',
            name='image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modules',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
