# Generated by Django 4.0.3 on 2022-04-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDegrees', '0005_modules_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdegrees',
            name='location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
